### ISSUE TITLE
Renaming symbols is incorrect

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran-lsp#23]
```
program expr2
implicit none

integer :: program

program = (2+3)*5
print *, program

end program
```
When you select the `program` variable, it will rename all occurrences of the term `program`, not just the variable. We must use LFortran's ASR to find the local variable "program" and only rename that.

**Comment by dylon** [comment]
We are blocked on fixing this until https://github.com/lfortran/lfortran/issues/5558 is resolved. At the moment, lfortran misses some symbol locations so we perform a global replacement.

**Comment by certik** [comment]
This still does not work. It seems to be doing a global replacement.

There are two issues that I can see:

* silencing an LFortran failure (if that is the case --- not sure)
* doing global replacement, which I do not want

To fix this, let's add a settings option that will disable any silent failover; I will then enable this and then I want to see a clear error in the logs every time something fails. Then we can report all bugs and fix it.

**Comment by Pranavchiku** [comment]
I think this works for me:

<img width="364" alt="image" src="https://github.com/user-attachments/assets/a12fce4c-7991-467f-a1d1-72ecaa9b3396" />

on Rename

<img width="769" alt="image" src="https://github.com/user-attachments/assets/a0cd9717-ad18-4053-91ab-a5528a27dd7b" />

renamed variable

<img width="431" alt="image" src="https://github.com/user-attachments/assets/849b6a74-c69f-48d8-ab84-cb474892d928" />

**Comment by certik** [comment]
It seems to work now:

<img width="288" alt="image" src="https://github.com/user-attachments/assets/8f23ba2f-8cf3-4d71-878d-26f2722d1634" />

So I am going to close it.
