### ISSUE TITLE
Lookup symbols across modules does not work

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran-lsp#55]
```
$ cat a.f90 
module a
implicit none

integer :: x

contains

    subroutine f(n)
    integer, intent(in) :: n
    print *, n
    end subroutine

end module
$ cat expr2.f90 
program expr2
use a, only: x, f
implicit none

x = (2+3)*5
print *, x
call f(x)

end program
```

Here is the list of symbols:

<img width="553" alt="image" src="https://github.com/user-attachments/assets/75881bc8-d9b4-44fd-900a-80ca87ac6866" />

This is incorrect. Looking up "x" for example points to line 4 in `expr2.f90`, instead of line 4 in `a.f90`.

LFortran seems to return the correct list of symbols (correct files and lines):
```
$ lfortran --show-document-symbols expr2.f90 | jq
[
  {
    "kind": 2,
    "location": {
      "range": {
        "start": {
          "character": 1,
          "line": 0
        },
        "end": {
          "character": 10,
          "line": 12
        }
      },
      "uri": "uri"
    },
    "name": "a",
    "filename": "a.f90"
  },
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 5,
          "line": 7
        },
        "end": {
          "character": 18,
          "line": 10
        }
      },
      "uri": "uri"
    },
    "name": "f",
    "filename": "a.f90"
  },
  {
    "kind": 13,
    "location": {
      "range": {
        "start": {
          "character": 28,
          "line": 8
        },
        "end": {
          "character": 28,
          "line": 8
        }
      },
      "uri": "uri"
    },
    "name": "n",
    "filename": "a.f90"
  },
  {
    "kind": 13,
    "location": {
      "range": {
        "start": {
          "character": 12,
          "line": 3
        },
        "end": {
          "character": 12,
          "line": 3
        }
      },
      "uri": "uri"
    },
    "name": "x",
    "filename": "a.f90"
  },
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 1,
          "line": 0
        },
        "end": {
          "character": 11,
          "line": 8
        }
      },
      "uri": "uri"
    },
    "name": "expr2",
    "filename": "expr2.f90"
  },
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 17,
          "line": 1
        },
        "end": {
          "character": 17,
          "line": 1
        }
      },
      "uri": "uri"
    },
    "name": "f",
    "filename": "expr2.f90"
  },
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 14,
          "line": 1
        },
        "end": {
          "character": 14,
          "line": 1
        }
      },
      "uri": "uri"
    },
    "name": "x",
    "filename": "expr2.f90"
  }
]
```
So this seems to be a bug in `lfortran-lsp`.

**Comment by dylon** [comment]
With PR #56, this should be resolved.

**Comment by certik** [comment]
I am going to reopen this, since it still does not work.

First, the outline has incorrect contents:

<img width="656" alt="image" src="https://github.com/user-attachments/assets/97fc51f6-1f1b-430c-9b80-c1711889bcb9" />

As you can see, it contains `a`, and subtrees `expr2` and `f`. In `expr2:x` it points to line 4, but there is no "x" on line 4, see the screenshot. However, there is `x` in `a.f90` on line 4.

Next problem: I put cursor on "x" and press F12 to lookup a definition. I get:

<img width="912" alt="image" src="https://github.com/user-attachments/assets/01c5795e-4cc2-4986-950a-75c5eea07f49" />

So it is trying to open `a.f90`, but says it failed. You can see on the next tab that `a.f90` is actually opened, so the file is there.

**Comment by certik** [comment]
Ok, the lookup symbol definition now works and opens up the other module at the right line!

Thanks for fixing it.

There are still other issues, but those are separate: https://github.com/lfortran/lfortran-lsp/issues/60
